name: sign_translator

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  permission_handler: ^11.0.1
  google_mlkit_pose_detection: ^0.10.0

flutter:
  uses-material-design: true